site_name:      翻儿Cloud 官方使用文档 
site_url:       https://example.com # 请替换为您的网站域名

theme:
  name: material
  language: zh  # 设置默认语言为中文
  features:
    - navigation.expand
    - navigation.top
    - toc.follow
    - navigation.instant
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式

extra:
#  alternate:
#    - name: 中文（简体）
#      link: /
#      lang: zh
#    - name: English
#      link: /en/
#      lang: en
#    - name: 日本語
#      link: /ja/
#      lang: ja
#    - name: 한국어
#      link: /kr/
#      lang: ko

  analytics:
    # 请将 'G-XXXXXXXXXX' 替换为您的 Google Analytics 4 Measurement ID
    provider: google
    property: G-XXXXXXXXXX

plugins:
  - search:
      lang:
        - en
        - ja
        - zh
      # 注意：Material for MkDocs 的搜索插件目前不支持韩语（ko），多语言搜索将对韩语无效。
  - optimize

markdown_extensions:
  - toc:
      permalink: true

nav:
  - 📖 翻儿Cloud 官方地址: index.md
  - 📲 苹果手机:
      - shadowrocket使用教程: iPhone/shadowrocket.md 
      - shadowrocket更新订阅教程: iPhone/iosgxdy.md
      - Stash 使用教程: iPhone/Stash.md
      - Stash 更新订阅教程: iPhone/Stash-update.md
  - 📘 安卓手机:
      - Clash MetaForAndroid使用教程: Android/Clash-meta.md
      - Clash.Meta更新订阅教程: Android/Clashgengxindy.md
      - v2rayNG For Android使用教程: Android/v2rayNG.md
      - v2rayNG 更新订阅教程: Android/v2rayng-update.md
      - Surfboard 使用教程: Android/Surfboard.md
      - Surfboard 更新订阅教程: Android/Surfboard-updata.md
  - 📚 MacBook苹果电脑:
      - clashX Pro使用教程: MacBook/clashXPro.md
      - clashX Pro更新订阅教程: MacBook/clashXPro-update.md
      - clashverge使用教程: MacBook/clashverge.md
      - clashverge更新订阅教程: MacBook/clashverge-uodate.md
  - 💻 Windows微软电脑:
      - Clash Verge使用教程: Windows/ClashVerge.md
      - Clash Verge更新订阅教程: Windows/gengxindingyue.md
      - v2rayN 使用教程: Windows/v2rayN.md
      - v2rayN 更新订阅教程: Windows/v2rayn-update.md
  -   📶 路由器插件配置:
      - Helloworld 科学上网教程: Router/helloworld.md
      - MerlinClash 小猫咪教程: Router/Merlinclash.md

