site_name:      翻儿Cloud 官方使用文档 

theme:
  name: material
  language: zh  # 设置默认语言为中文

nav:
  - 📖 翻儿Cloud 官方地址: index.md
  - 📲 苹果手机:
      - shadowrocket使用教程: iPhone/shadowrocket.md 
      - shadowrocket更新订阅教程: iPhone/iosgxdy.md
  - 📘 安卓手机:
      - Clash MetaForAndroid使用教程: Android/Clash-meta.md
      - Clash.Meta更新订阅教程: Android/Clashgengxindy.md
      - v2rayNG For Android使用教程: Android/v2rayNG.md
      - v2rayNG 更新订阅教程: Android/v2rayng-update.md
  - 📚 MacBook苹果电脑:
      - clashX Pro使用教程: MacBook/clashXPro.md
      - clashX Pro更新订阅教程: MacBook/clashXPro-update.md
      - clashverge使用教程: MacBook/clashverge.md
      - clashverge更新订阅教程: MacBook/clashverge-uodate.md
  - 💻 Windows微软电脑:
      - Clash Verge使用教程: Windows/ClashVerge.md
      - Clash Verge更新订阅教程: Windows/gengxindingyue.md
      - v2rayN 使用教程: Windows/v2rayN.md
      - v2rayN 更新订阅教程: Windows/v2rayn-update.md
  -   📶 路由器插件配置:
      - Helloworld 科学上网教程: Router\helloworld.md
      - MerlinClash 小猫咪教程: Router\Merlinclash.md

